extraction:
  cpp:
    after_prepare: 
      - python report.py 4
  cobol:
    after_prepare: 
      - python report.py 4
  csharp:
    after_prepare: 
      - python report.py 4
  java:
    after_prepare: 
      - python report.py 4
  javascript:
    after_prepare: 
      - python report.py 4
  python:
    after_prepare: 
      - python report.py 4
